[package]
name = "dopechain_rust_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
dopechain_rust_lib = {path = "../dopechain-rust-lib"}
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full"] }
